- name: GET Component ADC
  uri:
    url: "https://{{ extra_nginx_controller_ip }}/api/v1/services/environments/env_{{ extra_nginx_controller_environment | lower }}/apps/app_{{ extra_app.name | lower }}.{{ extra_app.domain | lower }}/components/adc_{{ item.name | lower }}"
    method: GET
    headers:
      "Cookie": "{{ stats_session }}"
    return_content: yes
    validate_certs: no
    status_code: 200
  loop: "{{ extra_app.components }}"
  when: item.type == "adc"
  register: results

- debug:
    var: results

- name: GET Component API "user NOT authenticated"
  uri:
    url: "https://{{ extra_nginx_controller_ip }}/api/v1/services/environments/env_{{ extra_nginx_controller_environment | lower }}/apps/app_{{ extra_app.name | lower }}.{{ extra_app.domain | lower }}/components/no-auth_{{ item.name | lower }}"
    method: GET
    headers:
      "Cookie": "{{ stats_session }}"
    return_content: yes
    validate_certs: no
    status_code: 200
  loop: "{{ extra_app.components }}"
  when: item.type == "api"
  register: results

- debug:
    var: results

- name: GET Component API "Authenticated users"
  uri:
    url: "https://{{ extra_nginx_controller_ip }}/api/v1/services/environments/env_{{ extra_nginx_controller_environment | lower }}/apps/app_{{ extra_app.name | lower }}.{{ extra_app.domain | lower }}/components/auth_{{ item.name | lower }}"
    method: GET
    headers:
      "Cookie": "{{ stats_session }}"
    return_content: yes
    validate_certs: no
    status_code: 200
  loop: "{{ extra_app.components }}"
  when: item.type == "api" and item.identityProviders is defined
  register: results

- debug:
    var: results

- name: GET Component API "Admin users"
  uri:
    url: "https://{{ extra_nginx_controller_ip }}/api/v1/services/environments/env_{{ extra_nginx_controller_environment | lower }}/apps/app_{{ extra_app.name | lower }}.{{ extra_app.domain | lower }}/components/admin_{{ item.name | lower }}"
    method: GET
    headers:
      "Cookie": "{{ stats_session }}"
    return_content: yes
    validate_certs: no
    status_code: 200
  loop: "{{ extra_app.components }}"
  when: item.type == "api" and item.identityProviders is defined
  register: results

- debug:
    var: results





